import { createHash, randomBytes } from 'node:crypto';
import { dailyCameo } from './cameos.mjs';

export class ApiError extends Error {
  constructor(status, message, retryAt) { super(message); this.status = status; this.retryAt = retryAt; }
}
const DAY = 86400000;
const COOLDOWN = 60000;
const digest = value => createHash('sha256').update(value).digest('hex');
const number = value => Number(value);

export function validateOrder(body) {
  if (!body || typeof body !== 'object' || Array.isArray(body)) throw new ApiError(400, 'Invalid order.');
  if (!['buy', 'sell'].includes(body.side)) throw new ApiError(400, 'Choose buy or sell.');
  if (typeof body.requestId !== 'string' || !/^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(body.requestId)) throw new ApiError(400, 'Invalid order reference.');
  if (body.website) throw new ApiError(400, 'Unable to accept this order.');
  const clean = (value, max, label) => {
    if (value === undefined) return '';
    if (typeof value !== 'string') throw new ApiError(400, `Invalid ${label}.`);
    const text = value.normalize('NFKC').trim();
    if ([...text].length > max) throw new ApiError(400, `${label} must be ${max} characters or fewer.`);
    if (/[\u0000-\u001f\u007f\u202a-\u202e\u2066-\u2069]/u.test(text)) throw new ApiError(400, `Please use plain text for your ${label}.`);
    if (/https?:\/\/|www\./i.test(text)) throw new ApiError(400, 'Links are not allowed in memos or names.');
    return text;
  };
  return { side: body.side, requestId: body.requestId, name: clean(body.name, 32, 'name'), note: clean(body.note, 160, 'memo') };
}

export async function createExchange(database, { now = Date.now } = {}) {
  const identity = database.kind === 'postgres' ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
  await database.transaction(async q => {
    await q(`CREATE TABLE IF NOT EXISTS exchange_state (id INTEGER PRIMARY KEY, price INTEGER NOT NULL, buys INTEGER NOT NULL, sells INTEGER NOT NULL, revision INTEGER NOT NULL, created_at BIGINT NOT NULL)`);
    await q(`INSERT INTO exchange_state (id,price,buys,sells,revision,created_at) VALUES (1,100,0,0,0,?) ON CONFLICT (id) DO NOTHING`, [now()]);
    await q(`CREATE TABLE IF NOT EXISTS orders (
      id ${identity}, side TEXT NOT NULL CHECK (side IN ('buy','sell')),
      created_at BIGINT NOT NULL, price_after INTEGER NOT NULL,
      visitor_key TEXT NOT NULL, request_id TEXT NOT NULL, payload_hash TEXT NOT NULL,
      display_name TEXT NOT NULL DEFAULT '', note TEXT NOT NULL DEFAULT '',
      moderation TEXT NOT NULL CHECK (moderation IN ('none','pending','approved','rejected')),
      reviewed_at BIGINT, UNIQUE (visitor_key,request_id))`);
    await q('CREATE INDEX IF NOT EXISTS orders_review ON orders (moderation,id)');
    await q('CREATE INDEX IF NOT EXISTS orders_visitor ON orders (visitor_key,created_at)');
    await q('CREATE INDEX IF NOT EXISTS orders_time ON orders (created_at,id)');
    await q('CREATE TABLE IF NOT EXISTS chart_daily (day BIGINT PRIMARY KEY, time BIGINT NOT NULL, price INTEGER NOT NULL)');
    await q('CREATE TABLE IF NOT EXISTS schema_migrations (name TEXT PRIMARY KEY)');
    const [chartMigration] = await q("SELECT name FROM schema_migrations WHERE name='chart-daily-v1'");
    if (!chartMigration) {
      await q(`INSERT INTO chart_daily (day,time,price)
        SELECT CAST(created_at / 86400000 AS INTEGER) * 86400000, created_at, price_after FROM orders
        WHERE id IN (SELECT MAX(id) FROM orders GROUP BY CAST(created_at / 86400000 AS INTEGER))
        ON CONFLICT (day) DO NOTHING`);
      await q("INSERT INTO schema_migrations (name) VALUES ('chart-daily-v1')");
    }
    await q('CREATE TABLE IF NOT EXISTS rate_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at BIGINT NOT NULL)');
    await q('CREATE INDEX IF NOT EXISTS rate_expiry ON rate_limits (expires_at)');
    await q('CREATE TABLE IF NOT EXISTS admin_sessions (token_hash TEXT PRIMARY KEY, expires_at BIGINT NOT NULL)');
  });

  async function quota(q, key, limit, window, timestamp) {
    const bucket = `${key}:${Math.floor(timestamp / window)}`;
    const expires = (Math.floor(timestamp / window) + 1) * window;
    const [row] = await q('SELECT count FROM rate_limits WHERE bucket=?', [bucket]);
    if (row && number(row.count) >= limit) throw new ApiError(429, 'A few too many requests. Try again later.', expires);
    await q('INSERT INTO rate_limits (bucket,count,expires_at) VALUES (?,1,?) ON CONFLICT (bucket) DO UPDATE SET count=rate_limits.count+1', [bucket, expires]);
  }

  function receipt(row, replay = false) {
    return { id: number(row.id), side: row.side, price: number(row.price_after), createdAt: number(row.created_at), review: row.moderation, nextOrderAt: number(row.created_at) + COOLDOWN, replay };
  }

  return {
    // Internal scheduler only: never exposed through the public HTTP API.
    // The unique visitor/request pair survives memo deletion and process restarts.
    dailyBuy() {
      return database.transaction(async q => {
        const timestamp = now(), day = Math.floor(timestamp / DAY) * DAY;
        const visitorKey = 'system:daily', requestId = `daily:${day}`;
        const [existing] = await q('SELECT * FROM orders WHERE visitor_key=? AND request_id=?', [visitorKey, requestId]);
        if (existing) return receipt(existing, true);
        const { name, note } = dailyCameo(day);
        const [state] = await q('SELECT price FROM exchange_state WHERE id=1');
        const price = number(state.price) + 1;
        const [row] = await q(`INSERT INTO orders (side,created_at,price_after,visitor_key,request_id,payload_hash,display_name,note,moderation,reviewed_at)
          VALUES ('buy',?,?,?,?,?,?,?,'approved',?) RETURNING *`, [timestamp, price, visitorKey, requestId, digest(requestId), name, note, timestamp]);
        await q('INSERT INTO chart_daily (day,time,price) VALUES (?,?,?) ON CONFLICT (day) DO UPDATE SET time=excluded.time,price=excluded.price', [day, timestamp, price]);
        await q('UPDATE exchange_state SET price=?,buys=buys+1,revision=revision+1 WHERE id=1', [price]);
        return receipt(row);
      });
    },
    async submit(input, visitorKey, networkKey) {
      const order = validateOrder(input);
      const payloadHash = digest(JSON.stringify([order.side, order.name, order.note]));
      return database.transaction(async q => {
        const timestamp = now();
        const [existing] = await q('SELECT * FROM orders WHERE visitor_key=? AND request_id=?', [visitorKey, order.requestId]);
        if (existing) {
          if (existing.payload_hash !== payloadHash) throw new ApiError(409, 'This order reference was already used. Close the ticket and try again.');
          return receipt(existing, true);
        }
        const [last] = await q('SELECT created_at FROM orders WHERE visitor_key=? ORDER BY id DESC LIMIT 1', [visitorKey]);
        if (last && number(last.created_at) + COOLDOWN > timestamp) throw new ApiError(429, 'One order per minute. Give the market a moment.', number(last.created_at) + COOLDOWN);
        await quota(q, `order:visitor:${visitorKey}`, 5, DAY, timestamp);
        await quota(q, `order:network:${networkKey}`, 30, DAY, timestamp);
        const [state] = await q('SELECT price FROM exchange_state WHERE id=1');
        const price = Math.max(1, number(state.price) + (order.side === 'buy' ? 1 : 0));
        const review = order.name || order.note ? 'pending' : 'none';
        const [row] = await q(`INSERT INTO orders (side,created_at,price_after,visitor_key,request_id,payload_hash,display_name,note,moderation) VALUES (?,?,?,?,?,?,?,?,?) RETURNING *`, [order.side, timestamp, price, visitorKey, order.requestId, payloadHash, order.name, order.note, review]);
        await q('INSERT INTO chart_daily (day,time,price) VALUES (?,?,?) ON CONFLICT (day) DO UPDATE SET time=excluded.time,price=excluded.price', [Math.floor(timestamp / DAY) * DAY, timestamp, price]);
        await q('UPDATE exchange_state SET price=?,buys=buys+?,sells=sells+?,revision=revision+1 WHERE id=1', [price, order.side === 'buy' ? 1 : 0, order.side === 'sell' ? 1 : 0]);
        await q('DELETE FROM rate_limits WHERE expires_at<?', [timestamp]);
        await q('DELETE FROM admin_sessions WHERE expires_at<?', [timestamp]);
        return receipt(row);
      });
    },

    snapshot() {
      return database.transaction(async q => {
        const [state] = await q('SELECT * FROM exchange_state WHERE id=1');
        const points = (await q('SELECT id,created_at,price_after FROM orders ORDER BY id DESC LIMIT 120')).reverse().map(row => ({ id: number(row.id), time: number(row.created_at), price: number(row.price_after) }));
        if (!points.length || points[0].id === 1) points.unshift({ id: 0, time: number(state.created_at), price: 100 });
        // Explicit projection: unapproved names and messages never leave the server.
        const orders = await q(`SELECT id,side,created_at,price_after,visitor_key,
          CASE WHEN moderation='approved' THEN display_name ELSE '' END AS name,
          CASE WHEN moderation='approved' THEN note ELSE '' END AS note
          FROM orders ORDER BY id DESC LIMIT 20`);
        const asOf = now();
        const since = asOf - DAY;
        const [stats] = await q('SELECT COUNT(*) AS trades, MAX(price_after) AS high, MIN(price_after) AS low FROM orders WHERE created_at>? AND created_at<=?', [since, asOf]);
        const [prior] = await q('SELECT price_after FROM orders WHERE created_at<=? ORDER BY created_at DESC,id DESC LIMIT 1', [since]);
        const reference = prior ? number(prior.price_after) : 100;
        const [last] = await q('SELECT created_at FROM orders ORDER BY id DESC LIMIT 1');
        const memos = await q("SELECT id,side,created_at,price_after,visitor_key,display_name AS name,note FROM orders WHERE moderation='approved' AND note<>'' ORDER BY id DESC LIMIT 20");
        const publicOrder = row => ({ id: number(row.id), side: row.side, time: number(row.created_at), price: number(row.price_after), name: (row.visitor_key === 'system:daily' ? row.name.replace(/ \(fictional\)$/, '') : row.name) || 'Guest', note: row.note, cameo: row.visitor_key === 'system:daily' });
        const daily = (await q('SELECT time,price FROM chart_daily ORDER BY day')).map(row => ({ time: number(row.time), price: number(row.price) }));
        return {
          price: number(state.price), change: number(state.price) - 100,
          total: number(state.buys) + number(state.sells), buys: number(state.buys), sells: number(state.sells),
          revision: number(state.revision), points,
          history: { anchor: { time: number(state.created_at), price: 100 }, daily },
          asOf, lastTradeAt: last ? number(last.created_at) : null,
          session: { since, trades: number(stats.trades), high: stats.high === null ? null : number(stats.high), low: stats.low === null ? null : number(stats.low), reference, change: number(state.price) - reference, changePercent: (number(state.price) - reference) / reference * 100 },
          orders: orders.map(publicOrder), memos: memos.map(publicOrder),
        };
      }, true);
    },

    async nextOrderAt(visitorKey) {
      return database.transaction(async q => {
        const [last] = await q('SELECT created_at FROM orders WHERE visitor_key=? ORDER BY id DESC LIMIT 1', [visitorKey]);
        return last ? number(last.created_at) + COOLDOWN : 0;
      }, true);
    },

    reviewQueue(status = 'pending', before = 2147483647) {
      if (!['pending', 'approved', 'rejected'].includes(status)) throw new ApiError(400, 'Invalid review filter.');
      return database.transaction(async q => {
        const rows = await q('SELECT id,side,created_at,display_name,note,moderation,visitor_key FROM orders WHERE moderation=? AND id<? ORDER BY id DESC LIMIT 21', [status, before]);
        const hasMore = rows.length > 20;
        const orders = rows.slice(0, 20).map(row => ({ id: number(row.id), side: row.side, time: number(row.created_at), name: row.visitor_key === 'system:daily' ? row.display_name.replace(/ \(fictional\)$/, '') : row.display_name, note: row.note, status: row.moderation }));
        const counts = { pending: 0, approved: 0, rejected: 0 };
        for (const row of await q("SELECT moderation,COUNT(*) AS total FROM orders WHERE moderation<>'none' GROUP BY moderation")) counts[row.moderation] = number(row.total);
        return { orders, next: hasMore ? orders.at(-1).id : null, counts };
      }, true);
    },

    moderate(id, action) {
      if (!['approve', 'reject', 'delete'].includes(action) || !Number.isSafeInteger(id) || id < 1) throw new ApiError(400, 'Invalid moderation action.');
      return database.transaction(async q => {
        const [row] = await q('SELECT moderation FROM orders WHERE id=?', [id]);
        if (!row) throw new ApiError(404, 'Order not found.');
        if (row.moderation === 'none') throw new ApiError(409, 'This order has no visitor text.');
        if (action === 'delete') {
          await q("UPDATE orders SET display_name='',note='',moderation='none',reviewed_at=? WHERE id=?", [now(), id]);
        } else await q('UPDATE orders SET moderation=?,reviewed_at=? WHERE id=?', [action === 'approve' ? 'approved' : 'rejected', now(), id]);
        await q('UPDATE exchange_state SET revision=revision+1 WHERE id=1');
        return { ok: true };
      });
    },

    checkRequestRate(networkKey, action = 'write') {
      return database.transaction(async q => {
        await q('DELETE FROM rate_limits WHERE expires_at<?', [now()]);
        await quota(q, `request:${action}:${networkKey}`, action === 'login' ? 8 : 40, action === 'login' ? 600000 : 60000, now());
      });
    },

    createAdminSession() {
      const token = randomBytes(32).toString('base64url');
      const expiresAt = now() + 8 * 3600000;
      return database.transaction(async q => {
        await q('DELETE FROM admin_sessions WHERE expires_at<?', [now()]);
        await q('INSERT INTO admin_sessions (token_hash,expires_at) VALUES (?,?)', [digest(token), expiresAt]);
        return token;
      });
    },
    authenticated(token) {
      if (!token || !/^[A-Za-z0-9_-]{43}$/.test(token)) return Promise.resolve(false);
      return database.transaction(async q => {
        const [session] = await q('SELECT expires_at FROM admin_sessions WHERE token_hash=?', [digest(token)]);
        return Boolean(session && number(session.expires_at) > now());
      }, true);
    },
    logout(token) { return database.transaction(q => q('DELETE FROM admin_sessions WHERE token_hash=?', [digest(token || '')])); },
  };
}
